//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19.04.2013 12:23:34
namespace WebApi.Svc
{
    
    /// <summary>
    /// There are no comments for WebApiCtx in the schema.
    /// </summary>
    public partial class WebApiCtx : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new WebApiCtx object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WebApiCtx(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("RF.BL.Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WebApi.Svc", typeName.Substring(11)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WebApi.Svc", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RF.BL.Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Holidays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<WorkCalendar> Holidays
        {
            get
            {
                if ((this._Holidays == null))
                {
                    this._Holidays = base.CreateQuery<WorkCalendar>("Holidays");
                }
                return this._Holidays;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<WorkCalendar> _Holidays;
        /// <summary>
        /// There are no comments for Governors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Governor> Governors
        {
            get
            {
                if ((this._Governors == null))
                {
                    this._Governors = base.CreateQuery<Governor>("Governors");
                }
                return this._Governors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Governor> _Governors;
        /// <summary>
        /// There are no comments for Assets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AssetValue> Assets
        {
            get
            {
                if ((this._Assets == null))
                {
                    this._Assets = base.CreateQuery<AssetValue>("Assets");
                }
                return this._Assets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AssetValue> _Assets;
        /// <summary>
        /// There are no comments for Holidays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHolidays(WorkCalendar workCalendar)
        {
            base.AddObject("Holidays", workCalendar);
        }
        /// <summary>
        /// There are no comments for Governors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGovernors(Governor governor)
        {
            base.AddObject("Governors", governor);
        }
        /// <summary>
        /// There are no comments for Assets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAssets(AssetValue assetValue)
        {
            base.AddObject("Assets", assetValue);
        }
    }
    /// <summary>
    /// There are no comments for RF.BL.Model.WorkCalendar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Holidays")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class WorkCalendar : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorkCalendar object.
        /// </summary>
        /// <param name="isWorkingDay">Initial value of IsWorkingDay.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WorkCalendar CreateWorkCalendar(bool isWorkingDay, global::System.DateTime date, global::System.Guid ID)
        {
            WorkCalendar workCalendar = new WorkCalendar();
            workCalendar.IsWorkingDay = isWorkingDay;
            workCalendar.Date = date;
            workCalendar.Id = ID;
            return workCalendar;
        }
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property IsWorkingDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsWorkingDay
        {
            get
            {
                return this._IsWorkingDay;
            }
            set
            {
                this.OnIsWorkingDayChanging(value);
                this._IsWorkingDay = value;
                this.OnIsWorkingDayChanged();
                this.OnPropertyChanged("IsWorkingDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsWorkingDay;
        partial void OnIsWorkingDayChanging(bool value);
        partial void OnIsWorkingDayChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType RF.BL.Model.Company in the schema.
    /// </summary>
    public partial class Company : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="lawFormValue">Initial value of lawFormValue.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(byte lawFormValue, string name, global::System.Guid ID)
        {
            Company company = new Company();
            company.lawFormValue = lawFormValue;
            company.Name = name;
            company.Id = ID;
            return company;
        }
        /// <summary>
        /// There are no comments for Property lawFormValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte lawFormValue
        {
            get
            {
                return this._lawFormValue;
            }
            set
            {
                this.OnlawFormValueChanging(value);
                this._lawFormValue = value;
                this.OnlawFormValueChanged();
                this.OnPropertyChanged("lawFormValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _lawFormValue;
        partial void OnlawFormValueChanging(byte value);
        partial void OnlawFormValueChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RF.BL.Model.Governor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Governors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Governor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Governor object.
        /// </summary>
        /// <param name="company">Initial value of Company.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        /// <param name="shortName">Initial value of ShortName.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Governor CreateGovernor(Company company, global::System.Guid companyId, string shortName, global::System.Guid ID)
        {
            Governor governor = new Governor();
            if ((company == null))
            {
                throw new global::System.ArgumentNullException("company");
            }
            governor.Company = company;
            governor.CompanyId = companyId;
            governor.ShortName = shortName;
            governor.Id = ID;
            return governor;
        }
        /// <summary>
        /// There are no comments for Property Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                if (((this._Company == null) 
                            && (this._CompanyInitialized != true)))
                {
                    this._Company = new Company();
                    this._CompanyInitialized = true;
                }
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                this._Company = value;
                this._CompanyInitialized = true;
                this.OnCompanyChanged();
                this.OnPropertyChanged("Company");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _CompanyInitialized;
        partial void OnCompanyChanging(Company value);
        partial void OnCompanyChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RF.BL.Model.AssetValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Assets")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AssetValue : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AssetValue object.
        /// </summary>
        /// <param name="insuranceTypeValue">Initial value of InsuranceTypeValue.</param>
        /// <param name="takingDate">Initial value of TakingDate.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="cashFlow">Initial value of CashFlow.</param>
        /// <param name="governorId">Initial value of GovernorId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AssetValue CreateAssetValue(byte insuranceTypeValue, global::System.DateTime takingDate, decimal value, decimal cashFlow, global::System.Guid governorId, global::System.Guid ID)
        {
            AssetValue assetValue = new AssetValue();
            assetValue.InsuranceTypeValue = insuranceTypeValue;
            assetValue.TakingDate = takingDate;
            assetValue.Value = value;
            assetValue.CashFlow = cashFlow;
            assetValue.GovernorId = governorId;
            assetValue.Id = ID;
            return assetValue;
        }
        /// <summary>
        /// There are no comments for Property InsuranceTypeValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte InsuranceTypeValue
        {
            get
            {
                return this._InsuranceTypeValue;
            }
            set
            {
                this.OnInsuranceTypeValueChanging(value);
                this._InsuranceTypeValue = value;
                this.OnInsuranceTypeValueChanged();
                this.OnPropertyChanged("InsuranceTypeValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _InsuranceTypeValue;
        partial void OnInsuranceTypeValueChanging(byte value);
        partial void OnInsuranceTypeValueChanged();
        /// <summary>
        /// There are no comments for Property TakingDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime TakingDate
        {
            get
            {
                return this._TakingDate;
            }
            set
            {
                this.OnTakingDateChanging(value);
                this._TakingDate = value;
                this.OnTakingDateChanged();
                this.OnPropertyChanged("TakingDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _TakingDate;
        partial void OnTakingDateChanging(global::System.DateTime value);
        partial void OnTakingDateChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Value;
        partial void OnValueChanging(decimal value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property CashFlow in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal CashFlow
        {
            get
            {
                return this._CashFlow;
            }
            set
            {
                this.OnCashFlowChanging(value);
                this._CashFlow = value;
                this.OnCashFlowChanged();
                this.OnPropertyChanged("CashFlow");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _CashFlow;
        partial void OnCashFlowChanging(decimal value);
        partial void OnCashFlowChanged();
        /// <summary>
        /// There are no comments for Property GovernorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid GovernorId
        {
            get
            {
                return this._GovernorId;
            }
            set
            {
                this.OnGovernorIdChanging(value);
                this._GovernorId = value;
                this.OnGovernorIdChanged();
                this.OnPropertyChanged("GovernorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _GovernorId;
        partial void OnGovernorIdChanging(global::System.Guid value);
        partial void OnGovernorIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Governor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Governor Governor
        {
            get
            {
                return this._Governor;
            }
            set
            {
                this._Governor = value;
                this.OnPropertyChanged("Governor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Governor _Governor;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
